# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "d+/jMpirTvFi+j51RkXPtVcbVlLznaKWpeOOo6av/I47buCXUo3F/1cYYyUg6GAvPySiiao2hZPWGBWb7Uykh3Qn4OAAItm2ntS2MLyW6k8FT6jeMPZyisgttyVE4/szOp3oYbLEHPnkyH6sPtYW+VZePMsLmHZfd+0TWc21MVEDUF2y3Y+cZ4rNh1zoOoe/NXxZdqg/LWDxNci4Dj9/amYAChTCwmciLnI19cy1XJPUCCApx9ySMiWcJMl51k+TlMm102e0ucJp9+VytW9B/Hdxs5izP+WwX381adJJeOm7ZppzgQVCiDkrBvqOrZ0Erk30gpW5LOSwSFQKa5oTYlbyDlKMLH/Ch7Qnlflbd1a3jlrd8lademICDKV0Ry7QJFwu3Xx2PXVy+p2cEnSoUwxDp4GWgKin7XN/xeFsyciyV6ibcO+ANzF5GFfUNppeu00MddIcVoA5UfMUvcr4fEuIVFHOqutvREXMZUK2yhSMYZaU2ysodZXxx5+G08Cg5cC3kRi7TCc/d+jvs1Ph9rF0C6nUtuHxR/rCtoPJ443oxJkQuqPqZwIsQ5eS88P1JFYIvEhCDHyU6gMneJ3JzwArGuRzp44DRksoZKnLw42BrD7oDsLD6c/t8SbfyLfeQ5ug+ZYVM+Wz072bgjXEhsIkYpL7lQD48kBx9X5iMU0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml